version: '2'

services:
  # DataStax Enterprise with KillrVideo schema and search config
  dse:
    image: killrvideo/killrvideo-dse-external:1.0.6
    cap_add:
    - IPC_LOCK
    ulimits:
      memlock: -1
    environment:
      SERVICE_9042_NAME: cassandra
      SERVICE_8983_NAME: dse-search
      SERVICE_8182_NAME: gremlin
      EXTERNAL_CLUSTER_IP: $EXTERNAL_CLUSTER_IP
      KILLRVIDEO_DOCKER_IP: $KILLRVIDEO_DOCKER_IP
      USERNAME: $KILLRVIDEO_DSE_USERNAME
      PASSWORD: $KILLRVIDEO_DSE_PASSWORD 
